### ISSUE TITLE
[ports] Update ports according to new github repositories

### ISSUE THREAD

**Issue by sepen** [crux-arm/crux-ports-core-arm#1]
After being forced to migrate the crux-arm.nu site in a short time, we have move the repos to github and we have lost access via rsync to update repos. Instead we have httpup to serve them.

That's for what we have to replace the files in the ports package.

For example:
core-arm.rsync -> core-arm.httpup

This involves upgrading the version of the ports package.

**Comment by pitill0** [comment]
Updated ports port with these changes on core-arm and core-arm64 repositories:
- Updated release
- Updated sources with new .httpup files for repositories: core-arm/core-arm64, opt-arm/opt-arm64 and xorg-arm/xorg-arm64

**Comment by sepen** [comment]
This is marked as DONE. All these repos from the list have the changeset implemented.
